// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as FizzBuzz from "./codeChallenge/fizzBuzz.bs.js";
import * as FileSizeCalculation from "./codeChallenge/fileSizeCalculation.bs.js";

import '../../input.css'
;

function Challenge(Props) {
  var fizzBuzzitems = FizzBuzz.fizzBuzz(100).map(function (fizz) {
        return React.createElement("p", undefined, fizz);
      });
  var fileSizeCalitems = FileSizeCalculation.fileSizeCalculation(FileSizeCalculation.files).map(function (file) {
        return React.createElement("p", undefined, file);
      });
  return React.createElement(React.Fragment, undefined, React.createElement("p", undefined, fizzBuzzitems), React.createElement("p", undefined, fileSizeCalitems));
}

var make = Challenge;

export {
  make ,
}
/*  Not a pure module */
