// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import './index.css'
;

function App(Props) {
  var active = Props.active;
  var activeClass = active ? "text-green-600" : "text-red-600";
  return React.createElement("div", {
              className: "sm:mx-5 border-4 border-sky-500 " + activeClass + ""
            }, "Hello World");
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
