// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_math from "rescript/lib/es6/js_math.js";

import '../../input.css'
;

var myFacts = [
  {
    id: "fact1",
    question: "My name is",
    answer: "Tata"
  },
  {
    id: "fact2",
    question: "My name is",
    answer: "Tata"
  },
  {
    id: "fact3",
    question: "My name is",
    answer: "Tata"
  },
  {
    id: "fact4",
    question: "My name is",
    answer: "Tata"
  },
  {
    id: "fact5",
    question: "My name is",
    answer: "Tata"
  },
  {
    id: "fact6",
    question: "My name is",
    answer: "Tata"
  },
  {
    id: "fact7",
    question: "My name is",
    answer: "Tata"
  },
  {
    id: "fact8",
    question: "My name is",
    answer: "Tata"
  },
  {
    id: "fact9",
    question: "My name is",
    answer: "Tata"
  }
];

function Fact(Props) {
  var componentToHex = function (c) {
    var hex = c.toString(16);
    if (hex.length === 1) {
      return "0" + hex;
    } else {
      return hex;
    }
  };
  var generateRandomColor = function (mix) {
    var red = Js_math.random_int(0, 256);
    var green = Js_math.random_int(0, 256);
    var blue = Js_math.random_int(0, 256);
    red = (red + mix.r | 0) / 2 | 0;
    green = (green + mix.g | 0) / 2 | 0;
    blue = (blue + mix.b | 0) / 2 | 0;
    return "#" + componentToHex(red) + componentToHex(green) + componentToHex(blue);
  };
  var items = myFacts.map(function (fact, index) {
        var randomHex = generateRandomColor({
              r: 255,
              g: 255,
              b: 255
            });
        return React.createElement("div", {
                    id: fact.id,
                    style: {
                      backgroundColor: "" + randomHex + ""
                    }
                  }, React.createElement("p", undefined, React.createElement("strong", undefined, "Question " + String(index + 1 | 0) + ": "), fact.question), React.createElement("p", undefined, "Answer: " + fact.answer));
      });
  return React.createElement("section", {
              className: "flex flex-wrap justify-center"
            }, items);
}

var make = Fact;

export {
  myFacts ,
  make ,
}
/*  Not a pure module */
