// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

import '../../input.css'
;

var myFacts = [
  {
    id: "fact1",
    question: "My name is",
    answer: "Tata"
  },
  {
    id: "fact2",
    question: "My name is",
    answer: "Tata"
  },
  {
    id: "fact3",
    question: "My name is",
    answer: "Tata"
  },
  {
    id: "fact4",
    question: "My name is",
    answer: "Tata"
  },
  {
    id: "fact5",
    question: "My name is",
    answer: "Tata"
  },
  {
    id: "fact6",
    question: "My name is",
    answer: "Tata"
  },
  {
    id: "fact7",
    question: "My name is",
    answer: "Tata"
  },
  {
    id: "fact8",
    question: "My name is",
    answer: "Tata"
  },
  {
    id: "fact9",
    question: "My name is",
    answer: "Tata"
  }
];

function Fact(Props) {
  return React.createElement("div", undefined);
}

var make = Fact;

export {
  myFacts ,
  make ,
}
/*  Not a pure module */
