// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Axios from "axios";
import * as $$Promise from "@ryyppy/rescript-promise/src/Promise.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

var v2_base = "https://pokeapi.co/api/v2/pokemon/";

var result = $$Promise.$$catch(Axios.get(v2_base + "pikachu").then(function (data) {
          return Promise.resolve((console.log(data), undefined));
        }), (function (err) {
        if (err.RE_EXN_ID === $$Promise.JsError) {
          console.log(Belt_Option.getWithDefault(err._1.message, "Must be some non-error value"));
        } else {
          console.log("Some unknown error");
        }
        return Promise.resolve(undefined);
      }));

console.log(result);

export {
  v2_base ,
  result ,
}
/* result Not a pure module */
