// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Promise from "@ryyppy/rescript-promise/src/Promise.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

var v2_base = "https://pokeapi.co/api/v2/pokemon/";

$$Promise.$$catch(fetch(v2_base + "pikachu").then(function (data) {
          return Promise.resolve((console.log(data), undefined));
        }), (function (err) {
        if (err.RE_EXN_ID === $$Promise.JsError) {
          console.log(Belt_Option.getWithDefault(err._1.message, "Must be some non-error value"));
        } else {
          console.log("Some unknown error");
        }
        return Promise.resolve(undefined);
      }));

export {
  v2_base ,
}
/*  Not a pure module */
